# ==========================================
# Nginx Load Balancer：定義後端 Proxy Pool
# ==========================================
upstream sso_proxy_pool {
    # 輪詢調度 (Round Robin)
    server sso-poc-proxy1:80 max_fails=2 fail_timeout=5s;
    server sso-poc-proxy2:80 max_fails=2 fail_timeout=5s;
}

# ==========================================
# Nginx Virtual Server 配置：監聽 test.gd.com:80
# ==========================================
server {
    listen 80;
    server_name test.gd.com test1.gd.com test2.gd.com _;

    access_log /var/log/nginx/nginx_lb_access.log combined;

    location ~ ^/(css|js|lib)/ {
        proxy_pass http://sso_proxy_pool;
        proxy_set_header Host $proxy_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass http://sso_proxy_pool;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 5s;
        proxy_read_timeout 60s;
        proxy_send_timeout 60s;
    }
}