# 【關鍵修正】：允許哨兵在背景動態解析 Docker 域名，防止啟動時閃退
sentinel resolve-hostnames yes

port 26379
sentinel monitor mymaster redis-master 6379 2
sentinel auth-pass mymaster YourStrongPassword
sentinel down-after-milliseconds mymaster 5000
sentinel failover-timeout mymaster 30000
sentinel parallel-syncs mymaster 1